import { expect, test } from '@playwright/test'
import { createWorkspaceDatabase, routeWorkspaceData, failWorkspaceWrites } from '../helpers/workspace-data-db.mjs'
import { testToken } from '../helpers/notes-db.mjs'

let db
test.afterEach(async () => { await db.close() })

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-12-31T12:00:00'))
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', route => route.fulfill({ json: true, headers: { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*' } }))
  db = await createWorkspaceDatabase()
  await routeWorkspaceData(page, db)
})

async function add(page, { date = '2026-12-31', title, note = false, time = null }) {
  await page.goto(`/#/calendar/${date}`)
  if (note) {
    const content = page.getByLabel('오늘의 노트 내용')
    await content.fill(title)
    await page.getByRole('button', { name: '노트 저장', exact: true }).click()
    await expect(content).toBeFocused()
    return
  }
  await page.getByRole('button', { name: note ? '노트 추가' : '일정 추가', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: note ? '노트 추가' : '일정 추가' })
  await dialog.getByLabel(note ? '내용' : '제목', { exact: true }).fill(title)
  await dialog.getByLabel('날짜', { exact: true }).fill(date)
  if (time !== null) await dialog.getByLabel('시간 (선택)', { exact: true }).fill(time)
  if (note) await expect(dialog.getByLabel('시간 (선택)', { exact: true })).toHaveCount(0)
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog).toBeHidden()
}

test('월간 캘린더에서 날짜를 선택해 일정 빠르게 추가', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/#/calendar?month=2027-01')
  const addButton = page.getByRole('button', { name: '일정 추가', exact: true })
  await expect(addButton).toBeEnabled()
  await addButton.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: '일정 추가', exact: true })
  await expect(dialog.getByLabel('날짜', { exact: true })).toHaveValue('2027-01-01')
  await dialog.getByLabel('제목', { exact: true }).fill('빠르게 추가한 일정')
  await dialog.getByRole('button', { name: '날짜 달력 열기' }).click()
  await page.getByRole('button', { name: '2027년 1월 15일', exact: true }).click()
  await dialog.getByLabel('시간 (선택)', { exact: true }).fill('13:45')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(addButton).toBeFocused()
  await expect(page.getByRole('link', { name: '2027-01-15 상세 보기', exact: true })).toContainText('빠르게 추가한 일정')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await page.reload()
  await page.getByRole('link', { name: '2027-01-15 상세 보기', exact: true }).click()
  await page.getByRole('button', { name: '빠르게 추가한 일정 수정·삭제', exact: true }).click()
  await expect(page.getByLabel('시간 (선택)', { exact: true })).toHaveValue('13:45')
})

test('간단한 시간 입력과 Enter 저장, 빈 시간은 23:59로 저장', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/#/calendar/2026-12-31')
  for (const [raw, expected] of [['1', '01:00'], ['130', '01:30'], ['오후 1시', '13:00'], ['', '23:59']]) {
    const title = `시간 확인 ${raw || '종일'}`
    await page.getByRole('button', { name: '일정 추가', exact: true }).click()
    await page.getByLabel('제목', { exact: true }).fill(title)
    const input = page.getByLabel('시간 (선택)', { exact: true })
    if (raw !== '') await expect(input).toHaveValue('00:00')
    await input.fill(raw)
    await input.press('Enter')
    await expect(page.getByRole('dialog', { name: '일정 추가', exact: true })).toBeHidden()
    await page.reload()
    await page.getByRole('button', { name: `${title} 수정·삭제`, exact: true }).click()
    await expect(input).toHaveValue(expected)
    await page.getByRole('button', { name: '취소', exact: true }).click()
  }
  await page.getByRole('button', { name: '시간 확인 130 수정·삭제', exact: true }).click()
  await page.getByLabel('시간 (선택)', { exact: true }).fill('')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: '시간 확인 130 수정·삭제', exact: true }).click()
  await expect(page.getByLabel('시간 (선택)', { exact: true })).toHaveValue('23:59')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('모바일 일정 시간 입력·선택·23:59 설정과 잘못된 시간 차단', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/#/calendar/2026-12-31')
  await page.getByRole('button', { name: '일정 추가', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '일정 추가', exact: true })
  await dialog.getByLabel('제목', { exact: true }).fill('시간 입력 확인')
  const input = dialog.getByLabel('시간 (선택)', { exact: true })
  await input.fill('25:99')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  expect(await input.evaluate(element => element.validity.customError)).toBe(true)
  await expect(dialog).toBeVisible()
  await input.fill('14:37')
  const trigger = dialog.getByRole('button', { name: '시간 (선택) 선택 열기' })
  await trigger.click()
  await expect(page.getByRole('combobox', { name: '시간 (선택) 시', exact: true })).toContainText('14시')
  await page.getByRole('combobox', { name: '시간 (선택) 분', exact: true }).click()
  await page.getByRole('option', { name: '38분', exact: true }).click()
  await page.getByRole('button', { name: '선택 완료', exact: true }).click()
  await expect(input).toHaveValue('14:38')
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(page.getByRole('dialog', { name: '시간 (선택) 선택', exact: true })).toHaveCSS('opacity', '1')
  await page.screenshot({ path: 'test-results/calendar-time-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '23:59로 설정' }).click()
  await expect(input).toHaveValue('23:59')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await page.reload()
  await page.getByRole('button', { name: /시간 입력 확인/ }).click()
  await expect(page.getByLabel('시간 (선택)', { exact: true })).toHaveValue('23:59')
})

test('일정·노트 CRUD와 오늘 목록, 연도 경계 D-day 및 저장 유지', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/#/calendar')
  await add(page, { title: '오늘 수업', time: '14:30' })
  await add(page, { title: '오늘 휴강 안내', note: true })
  await add(page, { title: '새해 수업', date: '2027-01-01', time: '09:00' })
  await add(page, { title: '미래 노트 숨김', date: '2027-01-01', note: true })
  await add(page, { title: '지난 일정 숨김', date: '2026-12-30' })
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await expect(page.locator('[data-sonner-toast]')).toHaveCSS('background-color', 'color(srgb 0.967059 0.978039 0.962941)')
  await expect(page.locator('[data-sonner-toast] [data-close-button]')).toHaveCount(0)
  await page.getByRole('link', { name: '월간 캘린더', exact: true }).click()
  await expect(page.getByRole('table')).toContainText('오늘 수업')
  await expect(page.getByRole('table')).not.toContainText('오늘 휴강 안내')
  await expect(page.getByRole('table')).not.toContainText('미래 노트 숨김')
  await page.getByRole('link', { name: '나의 작업실', exact: true }).click()
  const today = page.getByRole('region', { name: '오늘 일정', exact: true })
  await expect(today).toContainText('오늘 수업')
  await expect(today).toContainText('14:30')
  await expect(today).toContainText('오늘 휴강 안내')
  await expect(today.getByRole('button', { name: /일정보기|노트보기/ })).toHaveCount(0)
  const note = today.getByRole('region', { name: '오늘 노트 내용' })
  await expect(note).toHaveText('오늘 휴강 안내')
  for (const width of [1440, 320]) {
    await page.setViewportSize({ width, height: 1000 })
    const listBounds = await today.getByRole('list', { name: '오늘 일정 목록' }).boundingBox()
    const noteBounds = await note.boundingBox()
    expect(noteBounds.x).toBeGreaterThan(listBounds.x + listBounds.width)
    expect(Math.abs(noteBounds.y - listBounds.y)).toBeLessThan(2)
    expect(Math.abs(noteBounds.height - listBounds.height)).toBeLessThan(2)
    const columns = await note.locator('..').locator('..').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').map(parseFloat))
    expect(Math.abs(columns[0] - columns[1])).toBeLessThan(2)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('tab', { name: '다가오는 일정', exact: true }).click()
  const upcoming = page.getByRole('region', { name: '다가오는 일정' })
  await expect(upcoming).toContainText('새해 수업')
  await expect(upcoming).toContainText('D-1')
  await expect(upcoming.getByRole('listitem')).toHaveText(['D-day오늘 수업2시간 30분 남음', 'D-1새해 수업21시간 0분 남음'])
  await expect(upcoming).not.toContainText('미래 노트 숨김')
  await expect(upcoming).not.toContainText('지난 일정 숨김')
  await page.reload()
  await page.getByRole('tab', { name: '다가오는 일정', exact: true }).click()
  await expect(upcoming).toContainText('D-1')
  await page.screenshot({ path: 'test-results/calendar-workspace.png', fullPage: true })
  await page.getByRole('link', { name: '캘린더', exact: true }).click()
  await page.getByRole('link', { name: '2026-12-31 상세 보기', exact: true }).click()
  await page.getByRole('button', { name: '오늘 수업 수정·삭제', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '일정 수정' })
  await expect(dialog.getByLabel('시간 (선택)', { exact: true })).toHaveValue('14:30')
  await expect(dialog.getByRole('group', { name: '유형' })).toHaveCount(0)
  await dialog.getByLabel('제목').fill('변경된 일정')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await page.getByRole('button', { name: '변경된 일정 수정·삭제', exact: true }).click()
  await dialog.getByRole('button', { name: '삭제', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(page.getByRole('button', { name: '일정 추가', exact: true })).toBeFocused()
  await expect(page.getByRole('button', { name: '변경된 일정 수정·삭제', exact: true })).toHaveCount(0)
  await page.setViewportSize({ width: 320, height: 740 })
  await page.screenshot({ path: 'test-results/calendar-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '일정 추가', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '일정 추가', exact: true })).toBeFocused()
})

test('다가오는 일정의 하루 미만 남은 시간과 자동 갱신', async ({ page }) => {
  await add(page, { title: '곧 시작', time: '12:01' })
  await add(page, { title: '이미 시작', time: '11:00' })
  await add(page, { title: '오늘 종일', time: '' })
  await add(page, { title: '자정 일정', date: '2027-01-01', time: '00:00' })
  await add(page, { title: '정확히 하루', date: '2027-01-01', time: '12:00' })
  await add(page, { title: '종일 일정', date: '2027-01-01', time: '' })
  await page.goto('/#/workspace')
  await page.getByRole('tab', { name: '다가오는 일정', exact: true }).click()
  const list = page.getByRole('list', { name: '다가오는 일정 목록' })
  await expect(list).not.toContainText('이미 시작')
  await expect(list.getByRole('listitem')).toHaveText(['D-day곧 시작1분 남음', 'D-day오늘 종일11시간 59분 남음', 'D-1자정 일정12시간 0분 남음', 'D-1정확히 하루', 'D-1종일 일정'])
  await expect(list.locator('svg[aria-hidden="true"]')).toHaveCount(3)
  for (const width of [1440, 320]) {
    await page.setViewportSize({ width, height: 900 })
    await list.focus()
    await expect(list).toBeFocused()
    const row = list.getByRole('listitem').filter({ hasText: '오늘 종일' })
    const titleBounds = await row.getByText('오늘 종일', { exact: true }).boundingBox()
    const remainingBounds = await row.getByText('11시간 59분 남음', { exact: true }).boundingBox()
    const rowBounds = await row.boundingBox()
    expect(remainingBounds.x).toBeGreaterThanOrEqual(titleBounds.x + titleBounds.width)
    expect(Math.abs(remainingBounds.y + remainingBounds.height / 2 - titleBounds.y - titleBounds.height / 2)).toBeLessThan(2)
    expect(rowBounds.x + rowBounds.width - remainingBounds.x - remainingBounds.width).toBeLessThanOrEqual(14)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.clock.install({ time: new Date('2026-12-31T12:00:00') })
  await page.reload()
  await page.getByRole('tab', { name: '다가오는 일정', exact: true }).click()
  await page.clock.fastForward(30000)
  await expect(list).toContainText('1분 미만 남음')
  await expect(list).toContainText('23시간 59분 남음')
  await page.clock.fastForward(30000)
  await expect(list).not.toContainText('곧 시작')
  await page.clock.setSystemTime(new Date('2026-12-31T23:58:30'))
  await page.clock.fastForward(30000)
  await expect(list).not.toContainText('오늘 종일')
  await page.clock.fastForward(60000)
  await expect(list.getByRole('listitem').filter({ hasText: '종일 일정' })).toHaveText('D-day종일 일정23시간 59분 남음')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(0)
})

test('메모 드래그·방향키 이동과 화면 축소 시 경계 유지', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/#/calendar')
  await page.getByRole('button', { name: '작업실 메모 열기' }).click()
  const panel = page.getByRole('dialog', { name: '작업실 메모장' })
  const handle = page.getByRole('button', { name: '메모장 이동 (드래그 또는 방향키)' })
  await expect(panel.getByText('끌어서 이동', { exact: true })).toHaveCount(0)
  const initial = await panel.boundingBox()
  const grip = await panel.locator('svg.lucide-pencil-line').boundingBox()
  await page.mouse.move(grip.x + 10, grip.y + 10)
  await page.mouse.down()
  await page.mouse.move(grip.x + 460, grip.y - 90, { steps: 10 })
  await page.mouse.up()
  const moved = await panel.boundingBox()
  expect(moved.x).toBeGreaterThan(initial.x + 400)
  expect(moved.y).toBeLessThan(initial.y)
  await handle.focus()
  await page.keyboard.press('ArrowRight')
  expect((await panel.boundingBox()).x).toBeGreaterThan(moved.x)
  const beforeEmoji = await panel.boundingBox()
  await panel.getByRole('button', { name: '이모지 펼치기' }).click()
  await expect(panel.getByRole('group', { name: '이모지 추가' })).toBeVisible()
  expect((await panel.boundingBox()).x).toBe(beforeEmoji.x)
  expect((await panel.boundingBox()).y).toBe(beforeEmoji.y)
  await panel.getByRole('button', { name: '이모지 접기' }).click()
  await page.getByRole('textbox', { name: '작업실 메모 내용' }).fill('옮긴 자리에서도 작성')
  await page.setViewportSize({ width: 320, height: 740 })
  const small = await panel.boundingBox()
  expect(small.x).toBeGreaterThanOrEqual(0)
  expect(small.x + small.width).toBeLessThanOrEqual(320)
  expect(small.y + small.height).toBeLessThanOrEqual(740)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('button', { name: '작업실 메모 열기' })).toBeFocused()
})

test('저장 실패는 입력을 유지하고 성공 처리하지 않음', async ({ page }) => {
  await page.goto('/#/calendar/2026-12-31')
  await page.getByRole('button', { name: '일정 추가', exact: true }).click()
  await page.getByLabel('제목', { exact: true }).fill('저장 실패 초안')
  await failWorkspaceWrites(page)
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByLabel('제목', { exact: true })).toHaveValue('저장 실패 초안')
  await expect(page.locator('[data-sonner-toast]')).toContainText('저장하지 못했어요')
})
