import { expect, test } from '@playwright/test'
import { createWorkspaceDatabase, routeWorkspaceData, failWorkspaceWrites, callWorkspaceData } from '../helpers/workspace-data-db.mjs'
import { testToken } from '../helpers/notes-db.mjs'

let db
test('시간의 시·분을 숫자로 덮어쓰고 연속 숫자로 입력', async ({ page }) => {
  await page.goto('/#/calendar/2026-12-31')
  await page.getByRole('button', { name: '일정 추가', exact: true }).click()
  await page.getByLabel('제목', { exact: true }).fill('숫자 시간 입력')
  const time = page.getByLabel('시간 (선택)', { exact: true })
  await time.fill('1430')
  await time.press('Tab')
  await expect(time).toHaveValue('14:30')
  await time.click({ position: { x: 20, y: 20 } })
  expect(await time.evaluate(element => element.value.slice(element.selectionStart, element.selectionEnd))).toBe('14')
  await page.keyboard.type('9')
  await time.press('Tab')
  await expect(time).toHaveValue('09:30')
  await time.click({ position: { x: 52, y: 20 } })
  expect(await time.evaluate(element => element.value.slice(element.selectionStart, element.selectionEnd))).toBe('30')
  await page.keyboard.type('45')
  await time.press('Tab')
  await expect(time).toHaveValue('09:45')
  await time.focus()
  await page.keyboard.type('1835')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeHidden()
  await expect.poll(async () => (await callWorkspaceData(db, 'calendar_list')).find(entry => entry.title === '숫자 시간 입력')?.time).toBe('18:35')
})
test('저장 중 추가 입력과 날짜 이동에도 최신 초안 저장', async ({ page }) => {
  let saving = false
  await page.route('https://notes-test.invalid/**/manage_workspace_data', async route => {
    const request = route.request()
    if (request.method() !== 'OPTIONS' && request.postDataJSON().action === 'calendar_save') {
      saving = true
      await new Promise(resolve => setTimeout(resolve, 700))
    }
    return route.fallback()
  })
  await page.goto('/#/calendar/2026-12-31')
  const content = page.getByLabel('오늘의 노트 내용')
  await content.fill('첫 번째 초안')
  await expect.poll(() => saving).toBe(true)
  await expect(content).toBeEnabled()
  await content.fill('저장 중 수정한 최신 내용')
  await page.getByRole('link', { name: '월간 캘린더', exact: true }).click()
  await page.getByRole('link', { name: '2026-12-30 상세 보기', exact: true }).click()
  await content.fill('다른 날짜의 노트')
  await expect.poll(async () => (await callWorkspaceData(db, 'calendar_list')).filter(entry => entry.type === 'note').map(entry => [entry.date, entry.content]).sort()).toEqual([
    ['2026-12-30', '다른 날짜의 노트'],
    ['2026-12-31', '저장 중 수정한 최신 내용'],
  ])
  await page.reload()
  await expect(content).toHaveValue('다른 날짜의 노트')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(0)
})
test.afterEach(async () => { await db.close() })

test.beforeEach(async ({ page }) => {
  await page.clock.setFixedTime(new Date('2026-12-31T12:00:00'))
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', route => route.fulfill({ json: true, headers: { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*' } }))
  db = await createWorkspaceDatabase()
  await routeWorkspaceData(page, db)
})

test('모바일 날짜 팝업의 한국어 달력·연도 이동·선택·포커스 복귀', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/#/calendar/2026-12-31')
  await page.getByRole('button', { name: '일정 추가', exact: true }).click()
  await page.getByLabel('제목', { exact: true }).fill('새해 준비')
  const trigger = page.getByRole('button', { name: '날짜 달력 열기' })
  await trigger.click()
  const calendar = page.getByRole('dialog', { name: '날짜 선택' })
  await expect(calendar).toBeVisible()
  const bounds = await calendar.boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(320)
  await calendar.getByRole('button', { name: '다음 달', exact: true }).click()
  await calendar.getByRole('button', { name: '2027년 1월 1일', exact: true }).click()
  await expect(calendar).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(page.getByLabel('날짜', { exact: true })).toHaveValue('2027-01-01')
  await trigger.click()
  await expect(calendar).toHaveCSS('opacity', '1')
  await page.screenshot({ path: 'test-results/date-picker-mobile.png', fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog', { name: '일정 추가', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await page.goto('/#/calendar/2027-01-01')
  await expect(page.getByRole('button', { name: /새해 준비/ })).toBeVisible()
})

test('날짜 상세·여러 일정·노트 직접 편집·날짜별 분리·시간순 및 내부 스크롤', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/#/calendar')
  await expect(page.getByRole('columnheader')).toHaveText(['월', '화', '수', '목', '금', '토', '일'])
  expect(await page.getByRole('link', { name: '2026-12-01 상세 보기', exact: true }).evaluate(el => el.closest('td').cellIndex)).toBe(1)
  await page.getByRole('link', { name: '2026-12-31 상세 보기' }).click()
  await expect(page).toHaveURL(/#\/calendar\/2026-12-31$/)
  for (const [title, time] of [['오후 수업', '15:00'], ['아침 수업', '09:00'], ['점심 수업', '12:00'], ['종일 준비', '']]) {
    await page.getByRole('button', { name: '일정 추가', exact: true }).click()
    await page.getByLabel('제목', { exact: true }).fill(title)
    if (time) await page.getByLabel('시간 (선택)', { exact: true }).fill(time)
    await page.getByRole('button', { name: '저장', exact: true }).click()
  }
  await expect(page.getByLabel('제목', { exact: true })).toHaveCount(0)
  await page.getByLabel('오늘의 노트 내용', { exact: true }).fill('휴강 안내\n' + '긴 노트 내용\n'.repeat(30))
  await expect(page.getByRole('region', { name: '오늘의 노트', exact: true }).getByRole('status')).toHaveText('자동 저장됨')
  await expect(page.getByLabel('오늘의 노트 내용')).toBeFocused()
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '노트 추가', exact: true })).toHaveCount(0)
  await page.reload()
  await expect(page.getByRole('heading', { name: '일정 4개' })).toBeVisible()
  await page.getByRole('button', { name: '일정 추가', exact: true }).click()
  await expect(page.getByRole('group', { name: '유형' })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await page.getByRole('link', { name: '나의 작업실', exact: true }).click()
  const list = page.getByRole('list', { name: '오늘 일정 목록' })
  await expect(list.locator('li')).toHaveCount(4)
  const text = await list.locator('li').allTextContents()
  expect(text.map(t => t.slice(0, 5))).toEqual(['09:00', '12:00', '15:00', '종일종일 '])

  const note = page.getByRole('region', { name: '오늘 노트 내용' })
  expect(await note.evaluate(el => el.scrollHeight > el.clientHeight)).toBe(true)
  await note.focus()
  await page.keyboard.press('End')
  await expect.poll(() => note.evaluate(el => el.scrollTop)).toBeGreaterThan(0)
  await page.getByRole('link', { name: '오늘 상세 보기' }).click()
  await page.getByRole('link', { name: '월간 캘린더' }).click()
  await expect(page).toHaveURL(/month=2026-12$/)
  await page.goBack()
  await expect(page.getByRole('heading', { name: /2026. 12. 31/ })).toBeVisible()
  await page.goto('/#/calendar/2027-01-01')
  await page.getByLabel('오늘의 노트 내용', { exact: true }).fill('다음 날 노트')
  await expect(page.getByRole('region', { name: '오늘의 노트', exact: true }).getByRole('status')).toHaveText('자동 저장됨')
  await page.setViewportSize({ width: 320, height: 740 })
  await page.screenshot({ path: 'test-results/day-detail-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('기존 노트 제목 보존, 자동 저장과 내용 비우기', async ({ page }) => {
  await page.goto('/#/calendar/2026-12-31')
  await page.evaluate(() => localStorage.setItem('rokcha.calendar', JSON.stringify([{ id: crypto.randomUUID(), type: 'note', date: '2026-12-31', time: '', title: '기존 제목', content: '기존 내용' }])))
  await page.reload()
  await page.getByRole('button', { name: '기존 기록 가져오기', exact: true }).click()
  const dialog = page.getByRole('region', { name: '오늘의 노트' })
  await expect(dialog.getByLabel('제목', { exact: true })).toHaveCount(0)
  await expect(dialog.getByRole('group', { name: '유형' })).toHaveCount(0)
  const content = dialog.getByLabel('오늘의 노트 내용', { exact: true })
  await expect(content).toHaveValue('기존 제목\n\n기존 내용')
  await content.fill('   ')
  await expect(dialog.getByRole('status')).toHaveText('자동 저장됨')
  await content.fill('이날은 수업 없음\n교재 확인하기')
  await expect(dialog.getByRole('status')).toHaveText('자동 저장됨')
  await expect(content).toBeFocused()
  await page.reload()
  await expect(content).toHaveValue('이날은 수업 없음\n교재 확인하기')
  expect(await page.evaluate(() => localStorage.getItem('rokcha.calendar'))).toBeNull()
  await expect(content).toHaveValue('이날은 수업 없음\n교재 확인하기')
  await page.setViewportSize({ width: 320, height: 740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/note-content-mobile.png', fullPage: true })
  await expect(dialog.getByRole('button', { name: '노트 삭제', exact: true })).toHaveCount(0)
  await content.fill('')
  await expect(dialog.getByRole('status')).toHaveText('자동 저장됨')
  await page.reload()
  await expect(content).toHaveValue('')
})

test('노트 저장 실패 시 초안 유지 및 재시도', async ({ page }) => {
  await page.goto('/#/calendar/2026-12-31')
  await failWorkspaceWrites(page)
  const content = page.getByLabel('오늘의 노트 내용')
  await content.fill('실패해도 보관할 노트')
  await expect(page.getByRole('region', { name: '오늘의 노트', exact: true }).getByRole('alert')).toContainText('저장하지 못했어요')
  await expect(content).toHaveValue('실패해도 보관할 노트')
  await expect(page.getByRole('button', { name: '노트 저장' })).toHaveCount(0)
  await routeWorkspaceData(page, db)
  await page.getByRole('button', { name: '다시 시도', exact: true }).click()
  await expect(page.getByRole('region', { name: '오늘의 노트', exact: true }).getByRole('status')).toHaveText('자동 저장됨')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(0)
  await page.reload()
  await expect(content).toHaveValue('실패해도 보관할 노트')
})
