import { expect, test } from '@playwright/test'
import { createCareerDatabase, routeCareerEntries, callCareerEntries } from '../helpers/career-calendar-db.mjs'
import { routeWorkspaceData } from '../helpers/workspace-data-db.mjs'
import { testToken } from '../helpers/notes-db.mjs'

let db
test.beforeEach(async ({ page }) => {
  db = await createCareerDatabase()
  await page.clock.setFixedTime(new Date('2026-12-31T12:00:00'))
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', route => route.fulfill({ json: true, headers: { 'access-control-allow-origin': '*' } }))
  await routeWorkspaceData(page, db)
  await routeCareerEntries(page, db)
})
test.afterEach(async () => { await db.close() })

for (const width of [1440, 320]) test(`취업 캘린더 제목 표시·필수 시간·여러 링크·수정·삭제 ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 })
  const requests = []
  page.on('request', request => requests.push(request.url()))
  await page.goto('/#/career-calendar')
  await expect(page.getByRole('navigation', { name: '주 메뉴' })).toBeVisible()
  const nav = await page.getByRole('navigation', { name: '주 메뉴' }).getByRole('link').evaluateAll(links => links.map(link => link.getAttribute('href')))
  expect(nav.indexOf('#/career-calendar')).toBe(nav.indexOf('#/calendar') + 1)
  await expect(page.getByRole('columnheader')).toHaveText(['월', '화', '수', '목', '금', '토', '일'])
  const add = page.getByRole('button', { name: '취업 일정 추가', exact: true })
  await expect(add).toBeEnabled()
  await add.focus()
  await page.keyboard.press('Enter')
  const dialog = page.getByRole('dialog', { name: '취업 일정 추가', exact: true })
  await expect(dialog.getByLabel('제목', { exact: true })).toBeFocused()
  await dialog.getByLabel('제목', { exact: true }).fill('신입 공개 채용')
  await expect(dialog.getByLabel('마감 날짜', { exact: true })).toHaveValue('2026-12-31')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  expect(await dialog.getByLabel('마감 시간', { exact: true }).evaluate(input => input.validity.valueMissing)).toBe(true)
  await dialog.getByLabel('마감 시간', { exact: true }).fill('오후 6시')
  await dialog.getByLabel('메모', { exact: true }).fill('자기소개서 최종 확인\n포트폴리오 첨부')
  for (const [index, title, url] of [[1, '공식 모집 링크', 'https://apply.example/jobs'], [2, '자소서 작성 링크', 'https://apply.example/write']]) {
    await dialog.getByRole('button', { name: '링크 추가', exact: true }).click()
    await expect(dialog.getByLabel(`링크 ${index} 이름`)).toBeFocused()
    await dialog.getByLabel(`링크 ${index} 이름`).fill(title)
    await dialog.getByLabel(`링크 ${index} 주소`).fill(url)
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/career-editor-${width}.png`, fullPage: true })
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(add).toBeFocused()
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  const cell = page.getByRole('link', { name: '2026-12-31 취업 일정 상세 보기', exact: true })
  await expect(cell).toContainText('신입 공개 채용')
  await expect(cell.getByText('18:00', { exact: true })).toBeVisible()
  await expect(cell).not.toContainText('자기소개서')
  await expect(cell).not.toContainText('공식 모집 링크')
  await page.screenshot({ path: `test-results/career-month-${width}.png`, fullPage: true })
  expect(requests.some(url => /holidays|open-meteo/.test(new URL(url).hostname))).toBe(false)
  await cell.focus()
  await page.keyboard.press('Enter')
  const article = page.getByRole('article', { name: '신입 공개 채용', exact: true })
  await expect(article).toContainText('18:00 마감')
  await expect(article).toContainText('포트폴리오 첨부')
  await expect(article.getByRole('link', { name: '자소서 작성 링크 (새 탭)', exact: true })).toHaveAttribute('href', 'https://apply.example/write')
  await page.context().route('https://apply.example/**', route => route.fulfill({ contentType: 'text/html', body: '<title>지원 페이지</title>' }))
  const popupPromise = page.waitForEvent('popup')
  await article.getByRole('link', { name: '공식 모집 링크 (새 탭)', exact: true }).click()
  const popup = await popupPromise
  await expect(popup).toHaveURL('https://apply.example/jobs')
  await popup.close()
  await page.reload()
  await expect(article).toContainText('포트폴리오 첨부')
  await article.getByRole('button', { name: '신입 공개 채용 수정', exact: true }).click()
  const editor = page.getByRole('dialog', { name: '취업 일정 수정', exact: true })
  await editor.getByLabel('메모', { exact: true }).fill('수정한 메모\n제출 완료 확인')
  await editor.getByRole('button', { name: '링크 1 삭제', exact: true }).click()
  await expect(editor.getByLabel('링크 1 이름')).toBeFocused()
  await editor.getByLabel('링크 1 이름').fill('지원서 확인 링크')
  await editor.getByRole('button', { name: '저장', exact: true }).click()
  await expect(article.getByRole('button', { name: '신입 공개 채용 수정', exact: true })).toBeFocused()
  await expect(article.getByRole('link')).toHaveCount(1)
  await expect(article).toContainText('수정한 메모')
  await page.screenshot({ path: `test-results/career-detail-${width}.png`, fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await article.getByRole('button', { name: '신입 공개 채용 삭제', exact: true }).click()
  await expect(page.getByRole('button', { name: '취소', exact: true })).toBeFocused()
  await page.getByRole('button', { name: '취소', exact: true }).click()
  await expect(article.getByRole('button', { name: '신입 공개 채용 삭제', exact: true })).toBeFocused()
  await article.getByRole('button', { name: '신입 공개 채용 삭제', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '삭제', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toBeHidden()
  await expect(article).toHaveCount(0)
  await expect(add).toBeFocused()
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await page.reload()
  await expect(page.getByText('이 날짜에 등록한 취업 일정이 없어요.')).toBeVisible()
})

test('취업 일정 날짜 이동·월 이동·새로고침과 기존 캘린더 분리', async ({ page }) => {
  await page.goto('/#/career-calendar?month=2027-01')
  await page.getByRole('button', { name: '취업 일정 추가', exact: true }).click()
  await expect(page.getByLabel('마감 날짜', { exact: true })).toHaveValue('2027-01-01')
  await page.getByLabel('제목', { exact: true }).fill('최종 제출')
  await page.getByLabel('마감 시간', { exact: true }).fill('23:59')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await page.getByRole('link', { name: '2027-01-01 취업 일정 상세 보기', exact: true }).click()
  await page.getByRole('button', { name: '최종 제출 수정', exact: true }).click()
  await page.getByLabel('마감 날짜', { exact: true }).fill('2027-02-01')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page).toHaveURL(/#\/career-calendar\/2027-02-01$/)
  await page.reload()
  await expect(page.getByRole('article')).toContainText('23:59 마감')
  await page.getByRole('main').getByRole('link', { name: '취업 캘린더', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2027년 2월', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '이전 달', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2027년 1월', exact: true })).toBeVisible()
  await expect(page.getByRole('table')).not.toContainText('최종 제출')
  await page.getByRole('button', { name: '다음 달', exact: true }).click()
  await expect(page.getByRole('table')).toContainText('최종 제출')
  await page.getByRole('button', { name: '오늘', exact: true }).click()
  await expect(page.getByRole('heading', { name: '2026년 12월', exact: true })).toBeVisible()
  await page.goto('/#/calendar/2027-02-01')
  await expect(page.getByRole('heading', { name: '일정 0개', exact: true })).toBeVisible()
})

test('잘못된 링크 차단·저장 실패 초안 유지·삭제 실패 복구', async ({ page }) => {
  await page.goto('/#/career-calendar/2026-12-31')
  await page.getByRole('button', { name: '취업 일정 추가', exact: true }).click()
  await page.getByLabel('제목', { exact: true }).fill('남겨 둘 일정')
  await page.getByLabel('마감 시간', { exact: true }).fill('12:00')
  await page.getByRole('button', { name: '링크 추가', exact: true }).click()
  await page.getByLabel('링크 1 이름').fill('링크')
  await page.getByLabel('링크 1 주소').fill('javascript:alert(1)')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
  expect(await callCareerEntries(db, 'list')).toHaveLength(0)
  await page.getByLabel('링크 1 주소').fill('https://example.com')
  await page.getByLabel('메모', { exact: true }).fill('보관할 초안')
  await page.route('**/rpc/manage_career_entries', route => route.fulfill({ status: 503, json: {}, headers: { 'access-control-allow-origin': '*' } }))
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.locator('[data-sonner-toast]')).toContainText('요청을 처리하지 못했어요')
  await expect(page.getByLabel('메모', { exact: true })).toHaveValue('보관할 초안')
  await routeCareerEntries(page, db)
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('article')).toContainText('보관할 초안')
  await page.route('**/rpc/manage_career_entries', route => route.fulfill({ status: 503, json: {}, headers: { 'access-control-allow-origin': '*' } }))
  await page.getByRole('button', { name: '남겨 둘 일정 삭제' }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '삭제', exact: true }).click()
  await expect(page.locator('[data-sonner-toast]')).toContainText('요청을 처리하지 못했어요')
  await expect(page.getByRole('alertdialog')).toBeVisible()
  await expect(page.getByRole('article', { includeHidden: true })).toHaveCount(1)
  await routeCareerEntries(page, db)
  await page.getByRole('alertdialog').getByRole('button', { name: '삭제', exact: true }).click()
  await expect(page.getByRole('alertdialog')).toBeHidden()
  await expect(page.getByRole('article')).toHaveCount(0)
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
})
