import { expect, test } from '@playwright/test'
import { testToken } from '../helpers/notes-db.mjs'
import { createMotivationDatabase, callMotivation } from '../helpers/motivation-db.mjs'

let db
test.beforeEach(async ({ page }) => {
  db = await createMotivationDatabase()
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', async route => {
    const body = route.request().postDataJSON()
    const name = route.request().url().split('/').at(-1)
    const json = name === 'manage_motivation' ? await callMotivation(db, body.action, body.payload) : name === 'manage_workspace_data' ? body.action === 'memo_get' ? { content: '', revision: 1 } : [] : true
    await route.fulfill({ json })
  })
  await page.route('https://i.ytimg.com/**', route => route.fulfill({ status: 404, body: '' }))
  await page.route('https://www.youtube.com/embed/**', route => route.fulfill({ contentType: 'text/html', body: '<html><body>Player</body></html>' }))
})
test.afterEach(async () => { await db.close() })

for (const width of [1440, 320]) test(`${width}px 글귀·영상 저장, 재생, 수정·삭제 및 포커스`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 })
  await page.goto('/#/motivation')
  await page.getByRole('button', { name: '글귀 추가', exact: true }).click()
  await page.getByLabel('글귀', { exact: true }).fill('어제보다 한 걸음 더.\n나의 속도로 꾸준히.')
  await page.getByLabel('출처 · 지은이 (선택)').fill('나에게')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '글귀 추가', exact: true })).toBeFocused()
  await expect(page.locator('article')).toContainText('어제보다 한 걸음 더.')
  await page.getByRole('button', { name: '영상 추가', exact: true }).click()
  await page.getByLabel('유튜브 주소').fill('https://example.com/watch?v=M7lc1UVf-VE')
  await page.getByLabel('영상 제목').fill('다시 시작하는 마음')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('올바른 유튜브')
  await page.getByLabel('유튜브 주소').fill('https://youtu.be/M7lc1UVf-VE')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.locator('article')).toHaveCount(2)
  await page.reload()
  await expect(page.locator('article')).toHaveCount(2)
  await page.getByRole('button', { name: '다시 시작하는 마음 재생', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('iframe')).toHaveAttribute('src', /youtube\.com\/embed\/M7lc1UVf-VE/)
  expect(new URL(await page.locator('iframe').getAttribute('src')).searchParams.get('origin')).toBe('http://127.0.0.1:4175')
  await expect(page.locator('iframe')).toHaveAttribute('referrerpolicy', 'strict-origin-when-cross-origin')
  const previousPlayer = await page.locator('iframe').elementHandle()
  await page.getByRole('button', { name: '다시 불러오기', exact: true }).click()
  expect(await previousPlayer.evaluate(element => element.isConnected)).toBe(false)
  expect(new URL(await page.locator('iframe').getAttribute('src')).searchParams.get('autoplay')).toBe('0')
  await expect(page.getByText('영상 안의 재생 버튼을 눌러 주세요.')).toBeVisible()
  await expect(page.getByRole('link', { name: 'YouTube에서 보기' })).toHaveAttribute('href', 'https://www.youtube.com/watch?v=M7lc1UVf-VE')
  await page.getByRole('button', { name: '글귀', exact: true }).click()
  await expect(page.locator('iframe')).toHaveCount(0)
  await page.getByRole('button', { name: '수정', exact: true }).click()
  await page.getByLabel('글귀', { exact: true }).fill('오늘도 한 걸음.')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.locator('article')).toContainText('오늘도 한 걸음.')
  await page.getByRole('button', { name: '전체', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: `test-results/motivation-${width}.png`, fullPage: true })
  await page.getByRole('button', { name: '글귀', exact: true }).click()
  await page.getByRole('button', { name: '삭제', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '삭제', exact: true }).click()
  await expect(page.locator('article')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '글귀 추가', exact: true })).toBeFocused()
})

test('저장 실패 시 초안 유지 및 재시도', async ({ page }) => {
  await page.goto('/#/motivation')
  await page.getByRole('button', { name: '글귀 추가', exact: true }).click()
  await page.getByLabel('글귀', { exact: true }).fill('실패해도 다시')
  await page.route('**/rpc/manage_motivation', route => route.fulfill({ status: 503, body: '' }))
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
  await expect(page.getByLabel('글귀', { exact: true })).toHaveValue('실패해도 다시')
  await page.unroute('**/rpc/manage_motivation')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.locator('article')).toContainText('실패해도 다시')
})
