import { expect, test } from '@playwright/test'
import { routeWorkspaceData } from '../helpers/workspace-data-db.mjs'
import { callNotes, createNotesDatabase, testToken } from '../helpers/notes-db.mjs'

test.describe('메모함', () => {
  let db
  let actions
  let failAction
  let delayAction

  test.beforeEach(async ({ page }) => {
    db = await createNotesDatabase()
    actions = []
    failAction = ''
    delayAction = ''
    await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
    await page.route('https://notes-test.invalid/**', async route => {
      const request = route.request()
      const headers = { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*' }
      if (request.method() === 'OPTIONS') return route.fulfill({ status: 204, headers })
      if (request.url().endsWith('workspace_session_valid')) return route.fulfill({ json: true, headers })
      expect(request.headers()['x-workspace-session']).toBe(testToken)
      const { action, payload } = request.postDataJSON()
      actions.push(action)
      if (action === delayAction) await new Promise(resolve => setTimeout(resolve, 400))
      if (action === failAction) return route.fulfill({ status: 503, json: { message: 'test failure' }, headers })
      try {
        return await route.fulfill({ json: await callNotes(db, action, payload), headers })
      } catch {
        return await route.fulfill({ status: 400, json: { message: 'test SQL error' }, headers })
      }
    })
    await routeWorkspaceData(page, db)
  })

  test.afterEach(async () => { await db.close() })

  test('폴더 트리 선택, 내부 탐색, 배경 클릭 닫기', async ({ page }) => {
    await page.setViewportSize({ width: 320, height: 740 })
    const root = (await callNotes(db, 'list')).folders[0]
    await callNotes(db, 'create_folder', { name: '하위 폴더', parent_id: root.id })
    const child = (await callNotes(db, 'list')).folders.find(folder => folder.name === '하위 폴더')
    await callNotes(db, 'create_note', { folder_id: child.id, title: '계층 메모', content: '내부 내용' })
    await page.goto('/#/notes')
    await expect(page.getByRole('button', { name: /^계층 메모 내부/ })).toBeHidden()
    await expect(page.locator('button[id^="folder-title-"]')).toHaveCount(1)
    await page.locator('button[id^="folder-title-"]').filter({ hasText: '임시 폴더' }).click()
    await expect(page.getByRole('button', { name: /^계층 메모 내부/ })).toBeHidden()
    await page.locator('button[id^="folder-title-"]').filter({ hasText: '하위 폴더' }).click()
    await expect(page.getByRole('button', { name: /^계층 메모 내부/ })).toBeVisible()
    await page.getByRole('button', { name: '폴더 추가', exact: true }).click()
    const picker = page.getByRole('group', { name: '폴더 위치' })
    await expect(picker.getByRole('button', { name: '하위 폴더', exact: true })).toHaveAttribute('aria-pressed', 'true')
    await picker.getByRole('button', { name: '임시 폴더 접기' }).click()
    await expect(picker.getByRole('button', { name: '하위 폴더', exact: true })).toBeHidden()
    await picker.getByRole('button', { name: '임시 폴더 펼치기' }).click()
    await picker.getByRole('button', { name: '하위 폴더', exact: true }).click()
    await page.getByLabel('폴더 이름', { exact: true }).fill('손자 폴더')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    await expect(page.locator('button[id^="folder-title-"]')).toHaveAccessibleName('손자 폴더')
    await page.getByRole('button', { name: /^계층 메모 내부/ }).click()
    await page.getByLabel('제목', { exact: true }).fill('저장하지 않은 제목')
    await page.getByRole('button', { name: '메모함으로', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    await expect(page.getByRole('button', { name: /^계층 메모 내부/ })).toBeVisible()
    await page.getByRole('button', { name: '계층 메모 삭제', exact: true }).click()
    await page.locator('[data-slot="alert-dialog-overlay"]').click({ position: { x: 2, y: 2 } })
    await expect(page.getByRole('alertdialog')).toBeHidden()
    expect(actions.filter(action => action === 'delete_note')).toHaveLength(0)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await page.screenshot({ path: 'test-results/notes-nested-mobile.png', fullPage: true })
    await page.getByRole('button', { name: '전체 폴더', exact: true }).click()
    await expect(page.getByRole('button', { name: /^계층 메모 내부/ })).toBeHidden()
    await page.getByRole('button', { name: '임시 폴더 폴더 삭제', exact: true }).click()
    await expect(page.getByRole('alertdialog')).toContainText('하위 폴더 2개')
    await page.getByRole('button', { name: '폴더와 메모 삭제', exact: true }).click()
    await expect(page.getByRole('heading', { name: '첫 폴더를 만들어 보세요' })).toBeVisible()
    expect((await callNotes(db, 'list')).notes).toHaveLength(0)
  })
  test('폴더·메모 CRUD, 이동, 내부 최신순, 새로고침과 삭제 확인', async ({ page }) => {
    const errors = []
    page.on('pageerror', error => errors.push(error.message))
    await page.setViewportSize({ width: 1440, height: 1000 })
    await page.goto('/#/notes')
    await expect(page.getByRole('button', { name: '전체 폴더', exact: true })).toBeVisible()
    await page.getByRole('button', { name: '폴더 추가', exact: true }).click()
    await page.getByLabel('폴더 이름', { exact: true }).fill('아이디어')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    await page.getByRole('button', { name: '아이디어 이름 수정', exact: true }).click()
    await page.getByLabel('폴더 이름', { exact: true }).fill('생각 모음')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()

    await page.getByRole('button', { name: '임시 폴더에 메모 추가', exact: true }).click()
    await page.getByLabel('제목', { exact: true }).fill('첫 메모')
    await page.getByLabel('내용', { exact: true }).fill('잊지 않을 작은 생각')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    await page.getByRole('button', { name: /^첫 메모 잊지/ }).click()
    await expect(page).toHaveURL(/#\/notes\/[^?]+\?folder=/)
    await page.reload()
    await expect(page.getByLabel('내용', { exact: true })).toHaveValue('잊지 않을 작은 생각')
    expect((await page.getByLabel('내용', { exact: true }).boundingBox()).width).toBeGreaterThan(600)
    await page.getByLabel('제목', { exact: true }).fill('수정한 메모')
    await page.getByLabel('내용', { exact: true }).fill('조금 더 다듬은 생각')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    await page.getByRole('button', { name: '수정한 메모 폴더 이동', exact: true }).click()
    await page.getByRole('group', { name: '폴더', exact: true }).getByRole('button', { name: '생각 모음', exact: true }).click()
    await page.getByRole('button', { name: '이동', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    await expect(page.getByRole('button', { name: /^수정한 메모 조금/ })).toBeHidden()
    await page.getByRole('button', { name: '전체 폴더', exact: true }).click()

    await page.getByRole('button', { name: '생각 모음에 메모 추가', exact: true }).click()
    await page.getByLabel('제목', { exact: true }).fill('최근 메모')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('dialog')).toBeHidden()
    await expect(page.locator('main ul li').first()).toContainText('최근 메모')
    await page.reload()
    await expect(page.getByRole('button', { name: /^수정한 메모 조금/ })).toBeVisible()
    await expect(page.getByRole('button', { name: '전체 폴더', exact: true })).toBeVisible()
    await page.screenshot({ path: 'test-results/notes-desktop.png', fullPage: true })

    await page.getByRole('button', { name: '최근 메모 삭제', exact: true }).click()
    await page.getByRole('button', { name: '메모 삭제', exact: true }).click()
    await expect(page.getByRole('alertdialog')).toBeHidden()
    await page.getByRole('button', { name: '전체 폴더', exact: true }).click()
    await page.getByRole('button', { name: '생각 모음 폴더 삭제', exact: true }).click()
    await expect(page.getByRole('alertdialog')).toContainText('메모 1개')
    await expect(page.getByRole('button', { name: '취소', exact: true })).toBeFocused()
    await page.getByRole('button', { name: '취소', exact: true }).click()
    expect(actions.filter(action => action === 'delete_folder')).toHaveLength(0)
    await expect(page.getByRole('button', { name: '생각 모음 폴더 삭제', exact: true })).toBeFocused()
    await page.getByRole('button', { name: '전체 폴더', exact: true }).click()
    await page.getByRole('button', { name: '생각 모음 폴더 삭제', exact: true }).click()
    await page.getByRole('button', { name: '폴더와 메모 삭제', exact: true }).click()
    await expect(page.getByRole('alertdialog')).toBeHidden()
    await expect(page.getByRole('button', { name: '폴더 추가', exact: true })).toBeFocused()
    expect((await callNotes(db, 'list')).notes).toHaveLength(0)
    expect(errors).toEqual([])
  })

  test('320px 모바일, 긴 이름, 키보드 포커스, 중복 제출 방지와 실패 시 입력 유지', async ({ page }) => {
    await page.setViewportSize({ width: 320, height: 740 })
    await callNotes(db, 'create_folder', { name: '아주 긴 이름의 폴더도 화면을 벗어나지 않고 깔끔하게 표시되어야 합니다' })
    await page.goto('/#/notes')
    const addButton = page.getByRole('button', { name: '메모 추가', exact: true })
    await expect(addButton).toBeEnabled()
    await page.screenshot({ path: 'test-results/notes-mobile.png', fullPage: true })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    await addButton.focus()
    await page.keyboard.press('Enter')
    const editor = page.getByRole('region', { name: '새 메모', exact: true })
    await expect(page.getByLabel('제목', { exact: true })).toBeFocused()
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await page.getByLabel('제목', { exact: true }).fill('실패해도 유지될 제목')
    await page.getByLabel('내용', { exact: true }).fill('실패해도 유지될 내용')
    await expect(editor).toBeVisible()
    await page.screenshot({ path: 'test-results/notes-mobile-editor.png', fullPage: true })
    const bounds = await editor.boundingBox()
    expect(bounds.x).toBeGreaterThanOrEqual(0)
    expect(bounds.x + bounds.width).toBeLessThanOrEqual(320)
    await page.getByLabel('제목', { exact: true }).focus()
    await page.keyboard.press('Tab')
    await expect(page.getByLabel('내용', { exact: true })).toBeFocused()
    failAction = 'create_note'
    delayAction = 'create_note'
    await page.getByRole('button', { name: '저장', exact: true }).dblclick()
    await expect(editor.getByRole('alert')).toBeVisible()
    expect(actions.filter(action => action === 'create_note')).toHaveLength(1)
    await expect(page.getByLabel('제목', { exact: true })).toHaveValue('실패해도 유지될 제목')
    await expect(page.getByLabel('내용', { exact: true })).toHaveValue('실패해도 유지될 내용')
    failAction = ''
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(editor).toBeHidden()
    await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
    await expect(page.getByRole('button', { name: '실패해도 유지될 제목 실패해도 유지될 내용', exact: true })).toBeVisible()
    await page.getByRole('button', { name: '전체 폴더', exact: true }).click()

    await page.getByRole('button', { name: '임시 폴더 폴더 삭제', exact: true }).click()
    await expect(page.getByRole('alertdialog')).toHaveCSS('opacity', '1')
    await page.screenshot({ path: 'test-results/notes-mobile-delete.png', fullPage: true })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('alertdialog')).toBeHidden()
    await expect(page.getByRole('button', { name: '임시 폴더 폴더 삭제', exact: true })).toBeFocused()
  })

  test('불러오기 실패 후 재시도 및 마지막 폴더 삭제 후 다시 만들기', async ({ page }) => {
    failAction = 'list'
    await page.goto('/#/notes')
    await expect(page.getByRole('alert')).toBeVisible()
    failAction = ''
    await page.getByRole('button', { name: '다시 시도' }).click()
    await page.getByRole('button', { name: '임시 폴더 폴더 삭제', exact: true }).click()
    await page.getByRole('button', { name: '폴더와 메모 삭제', exact: true }).click()
    await expect(page.getByRole('heading', { name: '첫 폴더를 만들어 보세요' })).toBeVisible()
    await expect(page.getByRole('button', { name: '메모 추가', exact: true })).toBeDisabled()
    await page.getByRole('button', { name: '폴더 추가', exact: true }).first().click()
    await page.getByLabel('폴더 이름', { exact: true }).fill('다시 시작')
    await page.getByRole('button', { name: '저장', exact: true }).click()
    await expect(page.getByRole('button', { name: '메모 추가', exact: true })).toBeEnabled()
  })
})
