import { expect, test } from '@playwright/test'
import { createWorkspaceDatabase, routeWorkspaceData, failWorkspaceWrites } from '../helpers/workspace-data-db.mjs'
import { testToken } from '../helpers/notes-db.mjs'

let db
test.afterEach(async () => { await db.close() })

test.beforeEach(async ({ page }) => {
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', route => route.fulfill({ json: true, headers: { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*' } }))
  db = await createWorkspaceDatabase()
  await routeWorkspaceData(page, db)
})

async function selectTime(page, dialog, label, time) {
  const [hour, minute] = time.split(':')
  await dialog.getByRole('button', { name: `${label} 선택 열기`, exact: true }).click()
  await page.getByRole('combobox', { name: `${label} 시`, exact: true }).click()
  await page.getByRole('option', { name: `${hour}시`, exact: true }).click()
  await page.getByRole('combobox', { name: `${label} 분`, exact: true }).click()
  await page.getByRole('option', { name: `${minute}분`, exact: true }).click()
  await page.getByRole('button', { name: '선택 완료', exact: true }).click()
}

async function addLesson(page, name, days, start, end, color) {
  await page.getByRole('button', { name: '수업 추가', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '수업 추가' })
  await dialog.getByLabel('수업 이름', { exact: true }).fill(name)
  for (const day of ['월', '화', '수', '목', '금', '토', '일']) {
    const button = dialog.getByRole('button', { name: `${day}요일`, exact: true })
    if ((await button.getAttribute('aria-pressed') === 'true') !== days.includes(day)) await button.click()
  }
  await selectTime(page, dialog, '시작 시간', start)
  await selectTime(page, dialog, '종료 시간', end)
  await dialog.getByLabel('수업 메모', { exact: true }).fill('교재와 필기구 준비')
  await dialog.getByRole('button', { name: `${color} 색상` }).click()
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog).toBeHidden()
}

test('주간 반복·수업 CRUD·색상·새로고침·모바일 스크롤', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/#/workspace')
  await expect(page.getByRole('navigation', { name: '주 메뉴' }).getByRole('link')).toHaveText(['나의 작업실', '캘린더', '수업 시간표', '메모함', '링크함', '자료실', '뉴스함', '동기부여의 방', '날씨'])
  await page.getByRole('link', { name: '수업 시간표', exact: true }).click()
  await addLesson(page, '영어 회화', ['월', '수'], '09:00', '10:30', '녹차')
  await addLesson(page, '수학', ['화', '목'], '10:00', '12:00', '하늘')
  await addLesson(page, '드로잉', ['금'], '13:00', '15:00', '라벤더')
  await addLesson(page, '피아노', ['토'], '11:00', '12:00', '장미')
  await addLesson(page, '독서 모임', ['일'], '15:00', '16:30', '살구')
  await expect(page.getByRole('button', { name: '월요일 영어 회화 09:00–10:30 수정' })).toHaveAttribute('data-color', 'sage')
  await expect(page.getByRole('button', { name: '수요일 영어 회화 09:00–10:30 수정' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('button', { name: '금요일 드로잉 13:00–15:00 수정' })).toBeVisible()
  await page.screenshot({ path: 'test-results/timetable-desktop.png', fullPage: true })
  const lesson = page.getByRole('button', { name: '월요일 영어 회화 09:00–10:30 수정' })
  await lesson.focus()
  await page.keyboard.press('Enter')
  const edit = page.getByRole('dialog', { name: '수업 수정' })
  await expect(edit.getByLabel('수업 메모', { exact: true })).toHaveValue('교재와 필기구 준비')
  await edit.getByLabel('수업 이름', { exact: true }).fill('영어 토론')
  await edit.getByRole('button', { name: '민트 색상' }).click()
  await edit.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('button', { name: '수요일 영어 토론 09:00–10:30 수정' })).toHaveAttribute('data-color', 'teal')
  await page.setViewportSize({ width: 320, height: 740 })
  const grid = page.getByRole('region', { name: '월요일부터 일요일까지 주간 시간표' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(await grid.evaluate(el => el.scrollWidth > el.clientWidth)).toBe(true)
  await grid.evaluate(el => { el.scrollLeft = el.scrollWidth; el.scrollTop = 72 * 6 })
  expect(await grid.evaluate(el => el.scrollHeight === el.clientHeight && el.scrollTop === 0)).toBe(true)
  const weekdayHeader = page.getByRole('region', { name: '시간표 요일', exact: true })
  await expect.poll(() => weekdayHeader.evaluate(el => el.scrollLeft)).toBe(await grid.evaluate(el => el.scrollLeft))
  await weekdayHeader.evaluate(el => { el.scrollLeft = 0 })
  await expect.poll(() => grid.evaluate(el => el.scrollLeft)).toBe(0)
  await grid.evaluate(el => { el.scrollLeft = el.scrollWidth })
  await page.getByRole('button', { name: '일요일 독서 모임 15:00–16:30 수정' }).click()
  await expect(edit).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await edit.getByRole('button', { name: '삭제', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: '취소', exact: true }).click()
  await expect(edit).toBeVisible()
  await edit.getByRole('button', { name: '삭제', exact: true }).click()
  await page.getByRole('button', { name: '수업 삭제', exact: true }).click()
  await expect(edit).toBeHidden()
  await expect(page.getByRole('button', { name: '일요일 독서 모임 15:00–16:30 수정' })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '수업 추가', exact: true })).toBeFocused()
  await page.screenshot({ path: 'test-results/timetable-mobile.png', fullPage: true })
})

test('모바일 시분 선택·키보드·분 단위 저장 유지', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/#/timetable')
  await addLesson(page, '저녁 수업', ['월'], '21:17', '22:00', '민트')
  await page.reload()
  await page.getByRole('button', { name: '월요일 저녁 수업 21:17–22:00 수정' }).click()
  const dialog = page.getByRole('dialog', { name: '수업 수정' })
  await dialog.getByRole('button', { name: '시작 시간 선택 열기' }).click()
  const minutes = page.getByRole('combobox', { name: '시작 시간 분', exact: true })
  await minutes.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('option', { name: '17분', exact: true })).toBeFocused()
  await page.keyboard.press('ArrowDown')
  await expect(page.getByRole('option', { name: '18분', exact: true })).toBeFocused()
  await page.keyboard.press('Enter')
  await expect(minutes).toContainText('18분')
  await page.getByRole('button', { name: '선택 완료', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/time-picker-mobile.png', fullPage: true })
  await dialog.getByLabel('시작 시간', { exact: true }).fill('21:19')
  await dialog.getByLabel('종료 시간', { exact: true }).fill('22:05')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '월요일 저녁 수업 21:19–22:05 수정' })).toBeVisible()
})

test('잘못된 시간·요일 미선택·겹치는 수업·저장 실패', async ({ page }) => {
  await page.goto('/#/timetable')
  await addLesson(page, '기존 수업', ['월'], '09:00', '10:00', '녹차')
  await page.getByRole('button', { name: '수업 추가', exact: true }).click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('수업 이름', { exact: true }).fill('새 수업')
  await selectTime(page, dialog, '종료 시간', '08:00')
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('종료 시간')
  await selectTime(page, dialog, '종료 시간', '10:00')
  await dialog.getByRole('button', { name: '월요일', exact: true }).click()
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('요일')
  await dialog.getByRole('button', { name: '월요일', exact: true }).click()
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('겹치는 수업')
  await selectTime(page, dialog, '시작 시간', '10:00')
  await selectTime(page, dialog, '종료 시간', '11:00')
  await failWorkspaceWrites(page)
  await dialog.getByRole('button', { name: '저장', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('저장하지 못했어요')
  await expect(dialog.getByLabel('수업 이름', { exact: true })).toHaveValue('새 수업')
})
