import { randomUUID } from 'node:crypto'
import { expect, test } from '@playwright/test'
import { createWorkspaceDatabase, routeWorkspaceData, callWorkspaceData as call } from '../helpers/workspace-data-db.mjs'
import { testToken } from '../helpers/notes-db.mjs'

let db
test.beforeEach(async ({ page }) => {
  db = await createWorkspaceDatabase()
  for (const [title, completed] of [['첫 번째', false], ['완료 항목', true], ['세 번째', false]]) {
    await call(db, 'todo_save', { id: randomUUID(), revision: 0, title, completed })
  }
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', route => route.fulfill({ json: true, headers: { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*' } }))
  await routeWorkspaceData(page, db)
})
test.afterEach(async () => { await db?.close() })

const labels = page => page.getByRole('list', { name: '할 일 목록' }).locator('[data-todo-drag]')
const filter = (page, name) => page.getByRole('group', { name: '할 일 필터' }).getByRole('button', { name, exact: true })
const handle = (page, name) => page.getByRole('button', { name: `${name} 순서 변경` })

test('필터·키보드 순서·맨 뒤 추가·새로고침과 완료 후 순서 유지', async ({ page }) => {
  await page.goto('/#/workspace')
  await expect(page.getByRole('group', { name: '할 일 필터' }).getByRole('button')).toHaveCount(2)
  await expect(filter(page, '할 일')).toHaveAttribute('aria-pressed', 'true')
  await expect(labels(page)).toHaveText(['첫 번째', '세 번째'])
  await filter(page, '할 일').click()
  await expect(labels(page)).toHaveText(['첫 번째', '세 번째'])
  await handle(page, '세 번째').focus()
  await page.keyboard.press('ArrowUp')
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째'])
  await expect(handle(page, '세 번째')).toBeFocused()
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await filter(page, '할 일').click()
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째'])
  await page.getByRole('textbox', { name: '새 할 일' }).fill('새로 추가')
  await page.getByRole('button', { name: '할 일 추가', exact: true }).click()
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째', '새로 추가'])
  await page.getByRole('checkbox', { name: '세 번째 완료', exact: true }).click()
  await expect(page.getByRole('checkbox', { name: '세 번째 완료', exact: true })).toHaveCount(0)
  await expect(labels(page)).toHaveText(['첫 번째', '새로 추가'])
  await filter(page, '완료한 일').click()
  await expect(labels(page)).toHaveText(['세 번째', '완료 항목'])
  await handle(page, '세 번째').press('End')
  await expect(labels(page)).toHaveText(['완료 항목', '세 번째'])
  await page.reload()
  await expect(labels(page)).toHaveText(['첫 번째', '새로 추가'])
  await filter(page, '완료한 일').click()
  await expect(labels(page)).toHaveText(['완료 항목', '세 번째'])
})

test('데스크톱 드래그 저장·Escape 취소·실패 시 기존 순서와 포커스 유지', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/#/workspace')
  await expect(labels(page)).toHaveCount(2)
  await expect(page.getByText('위에 있을수록 먼저 할 일 · 손잡이로 순서 변경')).toHaveCount(0)
  await expect(page.getByRole('textbox', { name: '새 할 일' })).toHaveCSS('padding-left', '16px')
  await expect(page.getByRole('checkbox', { name: '첫 번째 완료', exact: true })).toHaveCSS('cursor', 'pointer')
  const start = await handle(page, '세 번째').boundingBox()
  const target = await handle(page, '첫 번째').boundingBox()
  await page.mouse.move(start.x + 10, start.y + 12)
  await page.mouse.down()
  await page.mouse.move(target.x + 10, target.y + 2, { steps: 8 })
  await page.mouse.up()
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째'])
  await expect(handle(page, '세 번째')).toBeFocused()
  await expect(page.locator('[data-sonner-toast] [data-close-button]')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/todos-desktop.png', fullPage: true })
  const source = await handle(page, '세 번째').boundingBox()
  const end = await handle(page, '첫 번째').boundingBox()
  await page.mouse.move(source.x + 10, source.y + 12)
  await page.mouse.down()
  await page.mouse.move(end.x + 10, end.y + 30, { steps: 8 })
  await page.keyboard.press('Escape')
  await page.mouse.up()
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째'])
  await page.route('https://notes-test.invalid/**/manage_workspace_data', route => {
    if (route.request().method() === 'OPTIONS' || route.request().postDataJSON().action !== 'todo_reorder') return route.fallback()
    return route.fulfill({ status: 503, json: {}, headers: { 'access-control-allow-origin': '*' } })
  })
  await handle(page, '세 번째').press('ArrowDown')
  await expect(page.locator('[data-sonner-toast]')).toContainText('저장하지 못했어요')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째'])
  await expect(handle(page, '세 번째')).toBeFocused()
  await page.reload()
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째'])
})

test('모바일 터치 드래그와 필터 빈 상태·완료 취소·추가', async ({ page, context }) => {
  await page.setViewportSize({ width: 375, height: 900 })
  await page.goto('/#/workspace')
  await expect(labels(page)).toHaveCount(2)
  await handle(page, '세 번째').scrollIntoViewIfNeeded()
  const start = await handle(page, '세 번째').boundingBox()
  const end = await handle(page, '첫 번째').boundingBox()
  const session = await context.newCDPSession(page)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: start.x + 10, y: start.y + 12 }] })
  for (let step = 1; step <= 8; step++) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: start.x + 10, y: start.y + 12 + (end.y + 2 - start.y - 12) * step / 8 }] })
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(labels(page)).toHaveText(['세 번째', '첫 번째'])
  await filter(page, '완료한 일').click()
  await page.getByRole('checkbox', { name: '완료 항목 완료', exact: true }).click()
  await expect(page.getByText('아직 완료한 일이 없어요.')).toBeVisible()
  await expect(page.getByRole('list', { name: '할 일 목록' })).toBeFocused()
  await page.getByRole('textbox', { name: '새 할 일' }).fill('모바일 추가')
  await page.getByRole('button', { name: '할 일 추가', exact: true }).click()
  await expect(filter(page, '할 일')).toHaveAttribute('aria-pressed', 'true')
  await expect(labels(page)).toHaveText(['세 번째', '완료 항목', '첫 번째', '모바일 추가'])
  await page.setViewportSize({ width: 320, height: 740 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/todos-mobile.png', fullPage: true })
})

test('긴 목록을 드래그할 때 자동 스크롤하며 마지막까지 이동', async ({ page }) => {
  for (let i = 0; i < 10; i++) await call(db, 'todo_save', { id: randomUUID(), revision: 0, title: `추가 ${i}`, completed: false })
  await page.goto('/#/workspace')
  const list = page.getByRole('list', { name: '할 일 목록' })
  await expect(labels(page)).toHaveCount(12)
  await handle(page, '첫 번째').scrollIntoViewIfNeeded()
  const start = await handle(page, '첫 번째').boundingBox()
  const bounds = await list.boundingBox()
  await page.mouse.move(start.x + 10, start.y + 10)
  await page.mouse.down()
  await page.mouse.move(start.x + 10, bounds.y + bounds.height - 3, { steps: 8 })
  await expect.poll(() => list.evaluate(el => el.scrollTop + el.clientHeight >= el.scrollHeight - 1)).toBe(true)
  await page.mouse.up()
  await expect(labels(page).last()).toHaveText('첫 번째')
  await page.reload()
  await expect(labels(page).last()).toHaveText('첫 번째')
})

test('다른 기기의 변경은 덮어쓰지 않고 새로고침 후 다시 정렬', async ({ page }) => {
  await page.goto('/#/workspace')
  await expect(labels(page)).toHaveText(['첫 번째', '세 번째'])
  await call(db, 'todo_save', { id: randomUUID(), revision: 0, title: '다른 기기에서 추가', completed: false })
  await handle(page, '첫 번째').press('ArrowDown')
  await expect(page.locator('[data-sonner-toast]')).toContainText('다른 곳에서 수정된 기록')
  await expect(labels(page)).toHaveText(['첫 번째', '세 번째'])
  await page.locator('[data-sonner-toast]').getByRole('button', { name: '다시 불러오기' }).click()
  await expect(labels(page)).toHaveText(['첫 번째', '세 번째', '다른 기기에서 추가'])
  await handle(page, '다른 기기에서 추가').press('Home')
  await expect(labels(page)).toHaveText(['다른 기기에서 추가', '첫 번째', '세 번째'])
})

test('전체 삭제 확인·취소·필터 밖 항목 삭제와 빈 목록 가드', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 900 })
  await page.goto('/#/workspace')
  await expect(labels(page)).toHaveCount(2)
  await expect(page.getByRole('button', { name: '할 일 새로고침' })).toHaveCount(0)
  await filter(page, '완료한 일').click()
  const trigger = page.getByRole('button', { name: '전체 삭제', exact: true })
  await trigger.click()
  const dialog = page.getByRole('alertdialog', { name: '전체 삭제하시겠습니까?' })
  await expect(dialog).toContainText('전체 3개')
  await expect(dialog.getByRole('button', { name: '취소', exact: true })).toBeFocused()
  expect((await call(db, 'todo_list')).length).toBe(3)
  await page.keyboard.press('Enter')
  await expect(dialog).toBeHidden()
  await expect(trigger).toBeFocused()
  await expect(labels(page)).toHaveCount(1)
  await trigger.click()
  await dialog.getByRole('button', { name: '전체 삭제', exact: true }).click()
  await expect(dialog).toBeHidden()
  await expect(labels(page)).toHaveCount(0)
  await expect(trigger).toBeDisabled()
  await expect(page.getByRole('textbox', { name: '새 할 일' })).toBeFocused()
  await expect(filter(page, '할 일')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await page.reload()
  await expect(labels(page)).toHaveCount(0)
  await expect(trigger).toBeDisabled()
})

test('전체 삭제 충돌·통신 실패 시 목록을 유지하고 다시 확인', async ({ page }) => {
  await page.goto('/#/workspace')
  await expect(labels(page)).toHaveCount(2)
  const trigger = page.getByRole('button', { name: '전체 삭제', exact: true })
  const dialog = page.getByRole('alertdialog', { name: '전체 삭제하시겠습니까?' })
  await trigger.click()
  await call(db, 'todo_save', { id: randomUUID(), revision: 0, title: '다른 기기 추가', completed: false })
  await dialog.getByRole('button', { name: '전체 삭제', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('삭제하지 못했어요')
  await expect(dialog.getByRole('button', { name: '전체 삭제', exact: true })).toBeDisabled()
  expect((await call(db, 'todo_list')).length).toBe(4)
  await dialog.getByRole('button', { name: '다시 불러오기' }).click()
  await expect(labels(page)).toHaveCount(3)
  await page.route('https://notes-test.invalid/**/manage_workspace_data', async route => {
    if (route.request().method() === 'OPTIONS' || route.request().postDataJSON().action !== 'todo_delete_all') return route.fallback()
    return route.fulfill({ status: 503, json: {}, headers: { 'access-control-allow-origin': '*' } })
  })
  await trigger.click()
  await dialog.getByRole('button', { name: '전체 삭제', exact: true }).click()
  await expect(dialog.getByRole('alert')).toBeVisible()
  await dialog.getByRole('button', { name: '취소', exact: true }).click()
  await expect(trigger).toBeFocused()
  await expect(labels(page)).toHaveCount(3)
  expect((await call(db, 'todo_list')).length).toBe(4)
})
