import { expect, test } from '@playwright/test'
import { createVocabularyDatabase, callVocabulary } from '../helpers/vocabulary-db.mjs'
import { routeWorkspaceData } from '../helpers/workspace-data-db.mjs'
import { testToken } from '../helpers/notes-db.mjs'

let db
test.beforeEach(async ({ page }) => {
  db = await createVocabularyDatabase()
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', route => route.fulfill({ json: true, headers: { 'access-control-allow-origin': '*' } }))
  await routeWorkspaceData(page, db)
  await page.route('**/rpc/manage_vocabulary', async route => {
    if (route.request().method() === 'OPTIONS') return route.fulfill({ status: 204, headers: { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*' } })
    const { action, payload } = route.request().postDataJSON()
    await route.fulfill({ json: await callVocabulary(db, action, payload), headers: { 'access-control-allow-origin': '*' } })
  })
})
test.afterEach(async () => { await db.close() })

for (const width of [1440, 320]) test(`단어 카드 테스트·뜻 공개·키보드 이동·다시 시작 ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 })
  await callVocabulary(db, 'save', { word: 'run', meanings: [{ part: '동사', text: '달리다' }, { part: '명사', text: '달리기' }] })
  await callVocabulary(db, 'save', { word: 'walk', meanings: [{ part: '동사', text: '걷다' }] })
  await page.goto('/#/vocabulary')
  await page.getByRole('link', { name: '단어 테스트', exact: true }).click()
  const deck = page.getByRole('region', { name: '단어 카드 테스트' })
  await expect(deck.getByRole('heading', { name: 'run', exact: true })).toBeVisible()
  await expect(deck.getByRole('status')).toHaveText('1 / 2')
  await expect(deck.getByText('달리다', { exact: true })).toHaveCount(0)
  await expect(deck.getByRole('button', { name: '이전 단어' })).toBeDisabled()
  await deck.getByRole('button', { name: '뜻 보기', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(deck.getByText('달리다', { exact: true })).toBeVisible()
  await expect(deck.getByText('달리기', { exact: true })).toBeVisible()
  await page.keyboard.press('Space')
  await expect(deck.getByText('달리다', { exact: true })).toHaveCount(0)
  await deck.getByRole('button', { name: '뜻 보기', exact: true }).click()
  await page.keyboard.press('ArrowRight')
  await expect(deck.getByRole('heading', { name: 'walk', exact: true })).toBeVisible()
  await expect(deck.getByRole('button', { name: '뜻 보기', exact: true })).toBeFocused()
  await expect(deck.getByText('걷다', { exact: true })).toHaveCount(0)
  await page.keyboard.press('ArrowRight')
  await expect(deck.getByRole('status')).toHaveText('2 / 2')
  await page.keyboard.press('ArrowLeft')
  await expect(deck.getByRole('heading', { name: 'run', exact: true })).toBeVisible()
  await expect(deck.getByText('달리다', { exact: true })).toHaveCount(0)
  await expect(deck.getByRole('article')).toHaveCSS('opacity', '1')
  await page.screenshot({ path: `test-results/vocabulary-test-${width}.png`, fullPage: true })
  await deck.getByRole('button', { name: '다음 단어' }).click()
  await deck.getByRole('button', { name: '뜻 보기', exact: true }).click()
  await deck.getByRole('button', { name: '처음부터' }).click()
  await expect(deck.getByRole('status')).toHaveText('1 / 2')
  await expect(deck.getByRole('button', { name: '뜻 보기', exact: true })).toBeFocused()
  await page.reload()
  await expect(deck.getByRole('status')).toHaveText('1 / 2')
  await expect(deck.getByText('달리다', { exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(0)
  await page.getByRole('link', { name: '공부방으로' }).click()
  await expect(page.getByRole('heading', { name: '영단어 공부방', exact: true })).toBeVisible()
})

test('단어 테스트 빈 목록·조회 실패 재시도·단일 카드', async ({ page }) => {
  await page.goto('/#/vocabulary/test')
  await expect(page.getByText('아직 테스트할 단어가 없어요. 공부방에서 단어를 추가해 주세요.')).toBeVisible()
  await callVocabulary(db, 'save', { word: 'keep', meanings: [{ part: '동사', text: '유지하다' }] })
  let fail = true
  await page.route('**/rpc/manage_vocabulary', route => fail && route.request().method() !== 'OPTIONS' ? route.fulfill({ status: 503, json: {}, headers: { 'access-control-allow-origin': '*' } }) : route.fallback())
  await page.reload()
  await expect(page.getByRole('alert')).toContainText('단어를 불러오지 못했어요')
  fail = false
  await page.getByRole('button', { name: '다시 시도' }).click()
  await expect(page.getByRole('heading', { name: 'keep', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '뜻 보기', exact: true }).click()
  await expect(page.getByText('유지하다', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '처음부터' }).click()
  await expect(page.getByText('유지하다', { exact: true })).toHaveCount(0)
  await expect(page.getByRole('button', { name: '이전 단어' })).toBeDisabled()
})

for (const width of [1440, 320]) test(`단어 검색·가리기 모드·편집과 포커스 ${width}`, async ({ page }) => {
  await page.setViewportSize({ width, height: 1000 })
  await callVocabulary(db, 'save', { word: 'run', meanings: [{ part: '동사', text: '달리다' }] })
  await callVocabulary(db, 'save', { word: 'walk', meanings: [{ part: '동사', text: '걷다' }] })
  await page.goto('/#/vocabulary')
  const list = page.getByRole('list', { name: '영단어 목록' })
  const detail = page.getByRole('region', { name: '선택한 단어', exact: true })
  const search = page.getByRole('textbox', { name: '단어 검색', exact: true })
  const hide = page.getByRole('switch', { name: '단어 가리기 모드' })
  await expect(page.getByRole('link', { name: '단어 테스트', exact: true })).toHaveAttribute('href', '#/vocabulary/test')
  await expect(page.getByRole('button', { name: '다시 불러오기', exact: true })).toHaveCount(0)
  await expect(list.getByRole('button')).toHaveCount(2)
  await search.fill('달리다')
  await expect(page.getByText('검색 결과가 없어요.')).toBeVisible()
  await search.fill(' RUN ')
  await expect(list.getByRole('button')).toHaveCount(1)
  await expect(list).toContainText('run')
  await search.fill('')
  await search.focus()
  await expect(search).toBeFocused()
  await page.screenshot({ path: `test-results/vocabulary-search-focus-${width}.png`, fullPage: true })
  await hide.focus()
  await page.keyboard.press('Space')
  await expect(hide).toBeChecked()
  await list.getByRole('button', { name: 'run', exact: true }).click()
  await expect(detail).toContainText('뜻을 가렸어요.')
  await expect(detail.getByText('달리다', { exact: true })).toHaveCount(0)
  await list.getByRole('button', { name: 'walk', exact: true }).click()
  await expect(detail.getByText('걷다', { exact: true })).toHaveCount(0)
  await hide.click()
  await expect(detail).toContainText('걷다')
  await list.getByRole('button', { name: 'run', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(detail.getByRole('heading', { name: '선택한 단어', exact: true })).toBeFocused()
  await expect(detail).toContainText('달리다')
  await expect(list).not.toContainText('달리다')
  const listBox = await list.boundingBox()
  const detailBox = await detail.boundingBox()
  if (width === 1440) expect(detailBox.x).toBeGreaterThanOrEqual(listBox.x + listBox.width)
  else expect(detailBox.y).toBeGreaterThanOrEqual(listBox.y + listBox.height)
  await detail.getByRole('button', { name: 'run 수정', exact: true }).click()
  await page.getByLabel('뜻 1', { exact: true }).fill('운영하다')
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(detail.getByRole('button', { name: 'run 수정', exact: true })).toBeFocused()
  await expect(detail).toContainText('운영하다')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
  await detail.getByRole('button', { name: 'run 삭제', exact: true }).click()
  await expect(page.getByRole('button', { name: '단어 추가', exact: true })).toBeFocused()
  await expect(list.getByRole('button', { name: 'run', exact: true })).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.goto('/#/vocabulary/test')
  await expect(page.getByRole('heading', { name: '단어 테스트', exact: true })).toBeVisible()
})

test('단어 추가·다중 뜻과 저장 실패 시 초안 유지', async ({ page }) => {
  await page.goto('/#/vocabulary')
  await page.getByRole('button', { name: '단어 추가', exact: true }).click()
  await page.getByLabel('영단어', { exact: true }).fill('keep')
  await page.getByLabel('뜻 1', { exact: true }).fill('유지하다')
  await page.getByRole('button', { name: '뜻 추가', exact: true }).click()
  await page.getByLabel('뜻 2', { exact: true }).fill('보관하다')
  await page.route('**/rpc/manage_vocabulary', route => route.fulfill({ status: 503, json: {} }))
  await page.getByRole('button', { name: '저장', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByLabel('뜻 1', { exact: true })).toHaveValue('유지하다')
  await expect(page.getByLabel('뜻 2', { exact: true })).toHaveValue('보관하다')
  await expect(page.getByRole('dialog').getByRole('alert')).toBeVisible()
})
