import { expect, test } from '@playwright/test'
import { createWorkspaceDatabase, routeWorkspaceData, failWorkspaceWrites } from '../helpers/workspace-data-db.mjs'
import { testToken } from '../helpers/notes-db.mjs'

let db
test.afterEach(async () => { await db.close() })

test.beforeEach(async ({ page }) => {
  await page.addInitScript(token => sessionStorage.setItem('rokcha.workspace-session', token), testToken)
  await page.route('https://notes-test.invalid/**', route => route.fulfill({ json: true, headers: { 'access-control-allow-origin': '*', 'access-control-allow-headers': '*' } }))
  db = await createWorkspaceDatabase()
  await routeWorkspaceData(page, db)
})

test('작업실 배치와 페이지 간 메모 편집·이모지·새로고침', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.goto('/#/workspace')
  const today = await page.getByRole('region', { name: '오늘 일정', exact: true }).boundingBox()
  const upcoming = await page.getByRole('region', { name: '할 일 리스트' }).boundingBox()
  const memo = await page.getByRole('region', { name: '작업실 메모', exact: true }).boundingBox()
  expect(today.width).toBe(upcoming.width)
  expect(upcoming.y).toBeGreaterThan(today.y + today.height)
  expect(memo.x).toBeGreaterThan(today.x + today.width)
  expect(Math.abs(memo.width * 2 - today.width)).toBeLessThan(2)
  expect(memo.height).toBeGreaterThan(today.height)
  await page.getByRole('textbox', { name: '작업실 메모 내용' }).fill('내 작업 메모')
  await page.getByRole('link', { name: '캘린더', exact: true }).click()
  await expect(page.getByRole('heading', { name: '캘린더', exact: true })).toBeVisible()
  const trigger = page.getByRole('button', { name: '작업실 메모 열기' })
  await trigger.focus()
  await page.keyboard.press('Enter')
  const input = page.getByRole('textbox', { name: '작업실 메모 내용' })
  await expect(input).toHaveValue('내 작업 메모')
  await expect(input).not.toHaveAttribute('placeholder')
  await expect(page.getByRole('button', { name: '초록 하트 이모지 추가' })).toBeHidden()
  await page.getByRole('button', { name: '이모지 펼치기' }).click()
  await input.focus()
  await input.evaluate(element => element.setSelectionRange(2, 4))
  await page.getByRole('button', { name: '초록 하트 이모지 추가' }).click()
  await expect(input).toHaveValue('내 💚 메모')
  await expect(input).toBeFocused()
  await page.getByRole('button', { name: '이모지 접기' }).click()
  await expect(page.getByRole('button', { name: '초록 하트 이모지 추가' })).toBeHidden()
  await expect(page.getByRole('status')).toContainText('저장됨')
  await page.keyboard.press('Escape')
  await expect(trigger).toBeFocused()
  await page.reload()
  await trigger.click()
  await expect(input).toHaveValue('내 💚 메모')
  await page.getByRole('heading', { name: '캘린더', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '작업실 메모장' })).toBeHidden()
  await trigger.click()
  await expect(input).toHaveValue('내 💚 메모')
  await page.getByRole('button', { name: '메모장 닫기' }).click()
  await page.getByRole('link', { name: '나의 작업실', exact: true }).click()
  await expect(input).toHaveValue('내 💚 메모')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(0)
  await page.screenshot({ path: 'test-results/workspace-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 320, height: 740 })
  for (const [title, link] of [['오늘 일정', '오늘 상세 보기'], ['다가오는 일정', '캘린더 보기']]) {
    await page.getByRole('tab', { name: title, exact: true }).click()
    const region = page.getByRole('region', { name: title, exact: true })
    const heading = await region.getByRole('tablist').boundingBox()
    const button = await region.getByRole('link', { name: link }).boundingBox()
    expect(button.y).toBeGreaterThanOrEqual(heading.y)
    expect(button.x + button.width).toBeLessThanOrEqual(320)
  }
  await trigger.click()
  const popup = page.getByRole('dialog', { name: '작업실 메모장' })
  await expect(popup).toBeVisible()
  const bounds = await popup.boundingBox()
  expect(bounds.x).toBeGreaterThanOrEqual(0)
  expect(bounds.x + bounds.width).toBeLessThanOrEqual(320)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/workspace-mobile.png', fullPage: true })
})

test('저장 실패 시 초안을 유지하고 실패 안내', async ({ page }) => {
  await page.goto('/#/workspace')
  await failWorkspaceWrites(page)
  await page.getByRole('textbox', { name: '작업실 메모 내용' }).fill('보관할 초안')
  await expect(page.getByRole('status')).toContainText('저장하지 못했어요')
  await expect(page.getByRole('textbox', { name: '작업실 메모 내용' })).toHaveValue('보관할 초안')
})

test('일정 키보드 전환과 할 일 추가·수정·완료·삭제·실패 복구', async ({ page }) => {
  await page.goto('/#/workspace')
  await page.getByRole('tab', { name: '오늘 일정', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('tab', { name: '다가오는 일정', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('tabpanel', { name: '오늘 일정', exact: true })).toBeHidden()
  const input = page.getByRole('textbox', { name: '새 할 일' })
  await input.fill('수업 준비')
  await page.getByRole('button', { name: '할 일 추가', exact: true }).click()
  await expect(input).toHaveValue('')
  await expect(input).toBeFocused()
  await page.getByRole('button', { name: '수업 준비 수정' }).click()
  await page.getByRole('textbox', { name: '할 일 수정' }).fill('교재 준비')
  await page.getByRole('button', { name: '수정 저장' }).click()
  await expect(page.getByRole('button', { name: '교재 준비 수정' })).toBeFocused()
  await page.getByRole('checkbox', { name: '교재 준비 완료' }).click()
  await expect(page.getByRole('checkbox', { name: '교재 준비 완료' })).toBeChecked()
  await page.reload()
  await expect(page.getByRole('checkbox', { name: '교재 준비 완료' })).toBeChecked()
  await page.setViewportSize({ width: 320, height: 740 })
  await page.getByRole('button', { name: '교재 준비 수정' }).click()
  await page.getByRole('textbox', { name: '할 일 수정' }).press('Escape')
  await expect(page.getByRole('button', { name: '교재 준비 수정' })).toBeFocused()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '교재 준비 삭제' }).click()
  await page.getByRole('button', { name: '취소', exact: true }).click()
  await expect(page.getByRole('button', { name: '교재 준비 삭제' })).toBeFocused()
  await page.getByRole('button', { name: '교재 준비 삭제' }).click()
  await page.getByRole('button', { name: '삭제', exact: true }).click()
  await expect(page.getByRole('checkbox')).toHaveCount(0)
  await expect(input).toBeFocused()
  await failWorkspaceWrites(page)
  await input.fill('실패해도 남는 할 일')
  await page.getByRole('button', { name: '할 일 추가', exact: true }).click()
  await expect(page.locator('[data-sonner-toast]')).toContainText('저장하지 못했어요')
  await expect(input).toHaveValue('실패해도 남는 할 일')
  await expect(page.locator('[data-sonner-toast]')).toHaveCount(1)
})
